stages:
  ingest:
    cmd: python3 src/ingest.py data/prepared
    deps:
    - src/ingest.py
    params:
    - ingest.dcount
    outs:
    - data/prepared

  split:
    cmd: python3 src/split.py data/prepared data/split
    deps:
    - src/split.py
    - data/prepared
    params:
    - ingest.dcount
    outs:
    - data/split

  # augment:
  #   cmd: python3 src/augment.py data/split data/augmented
  #   deps:
  #   - src/augment.py
  #   - data/split
  #   params:
  #   - ingest.dcount
  #   outs:
  #   - data/augmented

  transform:
    cmd: python3 src/transform.py data/augmented data/split data/transform
    deps:
    - src/transform.py
    # - data/augmented
    - data/split
    params:
    - ingest.dcount
    outs:
    - data/transform
  
  infer:
    cmd: python3 src/infer.py data/transform data/infer
    deps:
    - src/infer.py
    - data/transform
    params:
    - ingest.dcount
    outs:
    - data/infer

  train:
    cmd: python3 src/train.py data/transform data/train
    deps:
    - src/train.py
    - data/transform
    params:
    - ingest.dcount
    outs:
    - data/train

  predict:
    cmd: python3 src/predict.py data/train data/transform data/predict
    deps:
    - src/predict.py
    - data/train
    - data/transform
    params:
    - ingest.dcount
    outs:
    - data/predict

  compare:
    cmd: python3 src/compare.py data/infer data/predict data/store
    deps:
    - src/compare.py
    - data/infer
    - data/predict
    params:
    - ingest.dcount
    outs:
    - data/store

  exit:
    cmd: python3 src/exit.py data/store
    deps:
    - data/exit
    - data/store
    params:
    - ingest.dcount

#   infer:
#     cmd: python3 src/infer.py data/prepared data/transformed
#     deps:
#     - src/infer.py
#     - data/split
#     params:
#     - ingest.dcount
#     outs:
#     - data/infer

#   train:
#     cmd: python3 src/train.py data/split data/train
#     deps:
#     - src/infer.py
#     - data/split
#     params:
#     - ingest.dcount
#     outs:
#     - data/train

#   predict:
#     cmd: python3 src/predict.py data/train data/predict data/store
#     deps:
#     - data/train
#     - src/predict.py
#     params:
#     - ingest.dcount
#     outs:
#     - data/predict

#   compare:
#     cmd: python3 src/compare.py data/infer data/split data/store
#     deps:
#     - src/compare.py
#     - data/predict
#     - data/infer
#     params:
#     - ingest.dcount
#     outs:
#     - data/results
  
#   retrain:
#     cmd: python3 src/retrain.py data/results data/retrained data/predict data/store
#     deps:
#     - src/retrain.py
#     - data/results
#     - data/predict
#     params:
#     - ingest.dcount
#     outs:
#     - data/retrain

#   exit:
#     cmd: python3 src/exit.py data/compare data/store
#     deps:
#     - src/exit.py
#     - data/results
#     params:
#     - ingest.dcount
#     outs:
#     - data/store