dataset:
  name: Kar95
  path: archive
detectron_parameters:
  BASE_LR: 0.001
  BATCH_SIZE_PER_IMAGE: 64
  EVAL_PERIOD: 500
  GAMMA: 0.05
  IMS_PER_BATCH: 4
  MAX_ITER: 800
  NUM_CLASSES: 1
  NUM_WORKERS: 4
  SCORE_THRESH_TEST: 0.85
  WARM_UP_ITERS: 500
  config_file: COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml
ingest:
  dcount: 4
latest-run:
  folder: /home/yln1kor/Blob/Dummy/
option:
  custom: false
output:
  base_dir: output/
  model: output/model_final.pth
  results: results/
  results_pretrained: pretrained_results/
split:
  train: 0.9
  val: 0.1
validation:
  path: Val
version:
  best: v3
