dataset:
  path:  # Put path to dataset here

# Datatset
# --Images
# --Annotations

ingest:
  dcount: 3

split:
  infer : 0.1
  train : 0.3

parameters:
  config_file: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
  NUM_WORKERS: 2
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 1000
  BATCH_SIZE_PER_IMAGE: 512
  NUM_CLASSES: 1

output:
  model: output/model_final.pth
  results: results/
  base_dir: output/
  results_pretrained: pretrained_results/

option:
  custom: False